### ISSUE TITLE
Something went wrong while starting neon dreams

### ISSUE THREAD

**Issue by xSumedh** [robb0wen/synthwave-vscode#275]
I install Synthwave 84 theme vscode on mac, when enabling the extention it shows a Massege "Something went wrong while starting neon dreams"

**Comment by pdbrito** [comment]
I fixed this on my mac by moving my VS Code out of the downloads folder and into Applications

**Comment by sheim** [comment]
I'm also seeing this on Ubuntu 20.04

**Comment by onxades** [comment]
Also seeing on Ubuntu 22.04

**Comment by ireznik** [comment]
> I fixed this on my mac by moving my VS Code out of the downloads folder and into Applications

thank you!!! ❤️

**Comment by vivianintech** [comment]
@pdbrito My VSCode is always in the Application folder and the issue persists for me :(
